# Generated by Django 3.0.7 on 2020-06-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_touristspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
