# Generated by Django 3.0.7 on 2020-06-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_touristspot_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspot',
            old_name='image',
            new_name='photo',
        ),
    ]
